### ISSUE TITLE
Not showing up in Sublime 3.2.2

### ISSUE THREAD

**Issue by grahamreeds** [sindresorhus/editorconfig-sublime#93] opened 2021-01-25 13:25 UTC
Just tried installing in v3.2.2 and by the time you finish typing `EditorCo` into Package Control -> Install Package the only option is `EditorConfigSnippets` by mfuentesg.

**Comment by sindresorhus** [comment] 2021-01-25 14:36
Duplicate of #92

**Comment by sindresorhus** [comment] 2021-01-30 05:00
Should be fixed now.

**Closed by sindresorhus** 2021-01-30 05:00 UTC
